// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEfBVEopIe7eHKcwS0fLw-6xHlBwqLRy8',
    appId: '1:436011505012:web:24873621857cf5ff36c821',
    messagingSenderId: '436011505012',
    projectId: 'easy-dining-24380',
    authDomain: 'easy-dining-24380.firebaseapp.com',
    storageBucket: 'easy-dining-24380.appspot.com',
    measurementId: 'G-L7FKMWGWFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTmyna2S_8U-ynaAv7LiWUwSCRHf9-WJo',
    appId: '1:436011505012:android:c18f22c6b5036ca536c821',
    messagingSenderId: '436011505012',
    projectId: 'easy-dining-24380',
    storageBucket: 'easy-dining-24380.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBstqqmZFBBb8wrs2i5ELI2cf5FNw732qU',
    appId: '1:436011505012:ios:b468b88a731d7f1736c821',
    messagingSenderId: '436011505012',
    projectId: 'easy-dining-24380',
    storageBucket: 'easy-dining-24380.appspot.com',
    iosBundleId: 'com.example.easyDineIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBstqqmZFBBb8wrs2i5ELI2cf5FNw732qU',
    appId: '1:436011505012:ios:b468b88a731d7f1736c821',
    messagingSenderId: '436011505012',
    projectId: 'easy-dining-24380',
    storageBucket: 'easy-dining-24380.appspot.com',
    iosBundleId: 'com.example.easyDineIn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEfBVEopIe7eHKcwS0fLw-6xHlBwqLRy8',
    appId: '1:436011505012:web:44ceb7e71352b39136c821',
    messagingSenderId: '436011505012',
    projectId: 'easy-dining-24380',
    authDomain: 'easy-dining-24380.firebaseapp.com',
    storageBucket: 'easy-dining-24380.appspot.com',
    measurementId: 'G-RDBFL87JRM',
  );
}
